name: Sync OpenWRT Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions:
  contents: write

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
      release_tag: ${{ steps.get_release.outputs.release_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest OpenWRT release
        id: get_release
        run: |
          curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest > latest.json
          RELEASE_TAG=$(jq -r .tag_name latest.json)
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get_release.outputs.release_tag }})

          if [ "$HTTP_CODE" = "200" ]; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.check_release.outputs.release_exists == 'false'
        run: |
          gh release create "${{ steps.get_release.outputs.release_tag }}" \
            --title "AmneziaWG for OpenWrt ${{ steps.get_release.outputs.release_tag }}" \
            --notes "Auto build for OpenWrt ${{ steps.get_release.outputs.release_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-build:
    needs: sync-releases
    if: needs.sync-releases.outputs.release_exists == 'false'
    uses: ./.github/workflows/build-module.yml
    with:
      tag_name: ${{ needs.sync-releases.outputs.release_tag }}
